/**
 * Created by kasey.mccormick on 1/30/17.
 */
const regABform2 = {
    assetNumbers: {
        numberType: 'MERS',
        number: '44523',
        groupNumber: '4419873'
    },
    reportingPeriod: {
        begin: '09/26/2017',
        end: '12/01/2017'
    },
    generalInformation: {
        origination: {
            OriginalLoanPurpose: '5413',
            Originator: 'Freedom LLC',
            OriginatorLoanAmount: '$20,000',
            OriginalLoanMaturityDate: '8/12/16',
            OriginalAmortizationTerm: '',
            OriginalInterestRate: '',
            AccrualType: 'x28261',
            OriginalInterestRateType: '',
            OriginalInterestOnlyTerm: '',
            UnderwritingIndicator: '',
            OriginalLienPosition: 'x28261'
        },
        juniorLiens: {
            mostRecentJuniorLoanBalance: '',
            dateOfMostRecentJuniorLoanBalance: ''
        },
        firstMortgages: {
            MostRecentSeniorLoanAmount: '',
            DateOfMostRecentSeniorLoanAmount: '',
            LoanTypeOfMostSeniorLien: 'x28261',
            HybridPeriodOfMostSeniorLien: '',
            NegativeAmortizationLimitOfMostSeniorLien: '',
            OriginationDateOfMostSeniorLien: '',
            PrepaymentPenaltyIndicator: 'yes',
            NegativeAmortizationIndicator: 'yes',
            ModificationIndicator: 'no',
            NumberOfModifications: '2',
            MortgageInsuranceRequirementIndicator: 'no',
            BalloonIndicator: 'no',
            CoveredHighCostLoanIndicator: 'unknown',
            ServicerPlacedHazardInsurance: 'unknown',
            RefinanceCashOutAmount: '',
            TotalOriginationAndDiscountPoints: '$20,000',
            Broker: 'yes',
            Channel: 'x28261',
            NMLSCompanyNumber: '',
            BuyDownPeriod: '',
            loanDelinquencyAdvanceDaysCount: '',
            originalARMIndex:'x28261',
            armMargin:'',
            fullyIndextedInterestRate:'',
            initialFixedRatePeriodForHybridArm:'',
            initialInterestRateDecrease:'',
            initialInterestRateIncrease:'',
            postModificationIndexLookback:'',
            subsequentInterestRateRestPeriod:'',
            subsequentPaymentRestPeriod:'',
            armRoundIndicator:'x28261',
            armRoundPercentage:'',
            optionARMIndicator:'',
            paymentMethodAfterRecast:'x28261',
            postModificationInitialMinimumPayment:'',
            convertableIndicator:'yes',
            hELOCindicator:'yes',
            hELOCdrawPEriod:'',
            prepaymentPenaltyCalculation:'x28261',
            prepaymentPnaltyType:'x28261',
            prepaymentPenaltyTotalTerm:'',
            prepaymentPenaltyHardTerm:''


        }
    },
    negativeAmortization: {
        limit: '$20,006',
        recastPeriod: '',
        subsequent: '',
        negative: '',
        fixedPaymentPeriod: '',
        periodic: '',
        paymentCap: '',
        resetPeriod: '',
        paymentResetPeriod: '',
        minimumPayment: ''
    },
    propertyInformation: {
        geograpicLocation: '51',
        occupancyStatus: 'x28261',
        mostRecentOccupancyStatus: 'x28261',
        propertyType: 'x28261',
        mostRecentPropertyValue: '$133,000',
        mostRecentPropertyValuationType: 'x28261',
        mostRecentPropertyValuationDate: '8/12/16',
        mostRecentAvmModelName: 'x28261',
        mostRecentAVMConfidenceScore: '',
        originalCombinedLoanToValue: '',
        originalLoanToValue:''
    },
    obligorInformation: {
        originalNumberOfObligors: '',
        originalObligorCreditScore: '620',
        originalObligorCreditScoreType: 'FICO',
        mostRecentObligorCreditScore: '',
        mostRecentObligorCreditScoreType: '',
        dateOfMostRecentObligorCreditScore: '',
        obligorIncomeVerificationLevel: 'x28261',
        fourThousandFiveHundredAndSixTIndicator: 'yes',
        originatorFrontEdnDebtToIncome: '',
        orignitaroBackEndDti: '',
        obligorEmployementVerification: 'x28261',
        lengthOfEmploymentObligor: '',
        obligorAssetVerification: 'x28261',
        originalPlegedAssetsqualificationMethod: '',
        qualificationMethod:'x28261'
    },
    mortgageInsurance: {
        mortgageInsuraceCompanyName: '',
        mortgageInsuranceCoverage: '',
        poolInsuranceCompany: '',
        poolInsuranceStopLossPercent: '',
        mortgageInsuranceCoveragePlanType: 'x28261'

    },
    loanActivity: {
        assetAddedIndicator:'yes',
        remainingTermToMaturity: '',
        modificationIndicatorReportingPeriod: 'yes',
        nextPaymentDueDate: '',
        advancingMethod: 'x28261',
        servicingAdvanceMethodology: 'x28261',
        stopPrincipalAndInterestAdvanceDate: '',
        reportingPeriodBeginingLoanBalance: '',
        reportingPeriodBeginingShceduledLoanBalance: '',
        nextReportingPeriodPaymentAmountDue: '',
        reportingPeriodInterestRate: '',
        nextInterestRate: '',
        servicingFeePercentage: '',
        servicingFeeFlatFee: '',
        otherAssessedButUncollectedServicerFees: '',
        otherLoanLevelServicingFeesRetainedByTheServicer: '',
        scheduledInterestAmount: '',
        otherInterestAdjustments: '',
        ScheduledPrincipalAmount: '',
        otherPrincipalAdjustments: '',
        reportPeriodEndingActualBalance: '',
        reportingPeriodEndingScheduledBalance: '',
        reportingPeriodScheduledPaymentAmount: '',
        totalActualAmountPaid: '',
        actualInterestCollected: '',
        actualPrincipalCollected: '',
        actualOtherAmountsCollected: '',
        paidThroughDate: '',
        interestPaidThroughDate: '',
        paidInFullAmount: '',
        informationRelatedToServicerAdvances: '',
        servicerAdvancedAmountPrincipal: '',
        servicerAdvancedAmountsRepaidPrincipal: '',
        servicerAdvancesCumulativePrincipal: '',
        servicerAdvancedAmountInterest: '',
        servicerAdvancedAmountsRepaidInterest: '',
        servicerAdvancesCumulativeInterest: '',
        servicerAdvancedAmountTaxesAndInsurance: '',
        servicerAdvancedAmountRepaidTaxesAndInsurance: '',
        servicerAdvancesCumulativeTaxesAndInsurance: '',
        servicerAdvancedAmountCorporate: '',
        servicerAdvancedAmountRepaidCorporate: '',
        servicerAdvancesCumulativeCorporate: '',
        zeroBalanceLoans: '',
        zeroBalanceEffectiveDate: '',
        zeroBalanceCode: '',
        mostRecent12MonthPayHistory: '',
        numberOfPaymentsPastDue: '',
        informationRelatedToActivityOnArmLoans: '',
        rateAtNextReset: '',
        nextPaymentChangeDate: '',
        nextInterestRateChangeDate: '',
        paymentAtNextRest: '',
        exercisedArmConversionOptionIndicator: ''
    },
    servicerInformation: {
        primaryServicer: '',
        mostRecentServicingTransferReceivedDate: '',
        masterServicer: '',
        specialServicer: '',
        subservicer: ''
    },
    assetSubjectToDemand: {
        indicateSubjectOfDemand: '',
        statusOfAssetSubjectToDemand: '',
        repurchaseAmount: '',
        demandResolutionDate: '',
        repurchaser: '',
        repurchaseOrReplacementReason: ''
    },
    chargedOffInformation: {
        chargedOffPrincipalAmount: 'something new here',
        chargedOffInterestAmount: ''
    },
    lostIndicator: {
        indicateTypeOfLossMitigationServicerIsPursuingWithObligator: ''
    },
    loanModificationsInformation: {
        mostRecentLoanModificationEventType: '',
        effectiveDateOfTheMostRecentLoanModification: '',
        postModificationMaturityDate: '',
        postModificationInterestRateType: '',
        postModificationAmortizationType: '',
        postModificationInterestRate: '',
        postModificationFirstPaymentDate: '',
        postModificationLoanBalance: '',
        postModificationPrincipalAndInterstPayment: '',
        totalCapitalizedAmount: '',
        incomeVerificationIndicatorAtModification: '',
        modificationFrontEndDTI: '',
        modificationBackEndDTI: '',
        totalDeferredAmount: '',
        forgivenPrincipalAmountCumulative: '',
        forgivenPrincipalAmountReportingPeriod: '',
        forgivenInterestAmountCumulative: '',
        forgivenInterestAmountReportingPeriod: '',
        actualEndingBalanceTotalDebtOwed: '',
        scheduledEndingBalanceTotalDebtOwed: '',
        informationRelatedToARMLoanModifications: '',
        informationRelatedToArmLoanModifications: '',
        posModificationArmIndicator: '',
        postModificatioArmIndex: '',
        postModificationMargin: '',
        postModificationInterestResetPeriodIfChanged: '',
        postModificationNextResetDate: '',
        postModificationIndexLookback: '',
        postModificationArmRoundIndicator: '',
        postModificationArmRoundPercentage: '',
        postModificationInitialMinimumPayment: '',
        postModificationNextPaymentAdjustmentDate: '',
        postModificationArmPaymentRecastFrequency: '',
        postModificationLifetimeRateFloor: '',
        postModificationLifetimeRateCeiling: '',
        postModificationInitialInterestRateIncrease: '',
        postModificationInitialInterestRateDecrease: '',
        postModificationSubsequentInterestRateIncrease: '',
        postModificationSubsequentInterestRateDecrease: '',
        postModificationPaymentCap: '',
        postModificationPaymentMethodAfterRecast: '',
        postModificationArmInterestRateTeaserPeriod: '',
        postModificationPaymentTeaserPeriod: '',
        postModificationArmNegativeAmortizationIndicator: '',
        postModificationArmNegativeAmortization: ''
    },
    periodInformation: {
        postModificationInterestOnlyTerm: '',
        postModificationInterestOnlyLastPaymentDate: '',
        postModificationBalloonPaymentAmount: ''
    },
    stepLoansInformation: {
        postModificationInterestRateStepIndicator: '',
        postModificationStepInterestRate: '',
        postModificationStepDate: '',
        postModificationStepPrincipalAndInterest: '',
        postModificationNumberOfSteps: '',
        postModificationMaximumFutureRateUnderStepAgreemnet: '',
        postModificationDateOfMaximumRateUnderStepAgreement: '',
        nonInterestBearingPrincipalDeferredAmountCumulative: '',
        nonInterestBearingPrincipalDeferredAmountReportingPeriod: '',
        recoveryOfDeferredPrincipalReportingPeriod: '',
        nonInterestBearingDeferredPaidInFullAmount: '',
        nonInterestBearingDeferredInterestAndFeesAmountReportingPeriod: '',
        nonInterestBearingDeferredInterestFeesAmountCumulative: '',
        recoveryOfDeferredInterestAndFeesReportingPeriod: ''
    },
    modificationInformation: {
        mostRecentForebarancePlanOrTrialModificationStartDate: '',
        mostRecentForbearancePlanOrTrialModificationScheduledEndDate: '',
        mostRecentTrialModificationViolatedDate: ''
    },
    repaymentPlanInformation: {
        mostRecentRepaymentPlanStartDate: '',
        mostRecentRepaymentPlanScheduledEndDate: '',
        mostRecentRepaymentPlanViolatedDate: ''
    },
    shortSalesInformation: {
        shortSaleAcceptedOfferAmount: ''
    },
    mitigationExitInformation: {
        mostRecentLossMitigationExitDate: '',
        mostRecentLossMitigationExitCode: ''
    },
    foreclosureInformation: {
        AttorneyReferalDate: '',
        foreclosureDelayReason: '',
        foreclosureExitDate: '',
        foreclosureExitReason: '',
        NOIDate: ''
    },
    relatedToREOInformation: {
        mostRecentAcceptedREOOfferAmount: '',
        mostRecentAcceptedREOOfferDate: '',
        grossLiquidationProceeds: '',
        netSalesProceeds: '',
        reportingPeriodLossAmountPassedToIssuingEntity: '',
        cumulativeTotalLossAmountPassedToIssuingEntity: '',
        subsequentRecoveryAmount: '',
        evictionIndicator: '',
        REOExitDate: '',
        REOExitReason: ''
    },
    lossesInformation: {
        UPBAtLiquidation: '$20,000',
        servicingFeesClaimed: '$20,000',
        servicerAdvancedAmountsReimbursePrincipal: '$20,000',
        servicerAdvancedAmountsReimbursedInterest: '3.5%',
        servicerAdvancedAmountReimbursedTaxesAndInsurance: '$20,000',
        servicerAdvancedAmountReimbursedCorporate: '$20,000',
        REOManagementFees: '$20,000',
        cashForKeysCashForDeed: '$20,000',
        performanceIncentiveFees: '$20,000'
    },
    insuranceClaimsInformation: {
        MIClaimFiledDate: '8/12/16',
        MIClaimAmount: '$20,000',
        MIClaimPaidDate: '18/12/16',
        MIClaimPaidAmount: '$20,000',
        MIClaimDeniedRescindedDate: '8/12/16',
        MarketableTitleTransferredDate: '8/12/16'
    },
    delinquentLoansInformation: {
        nonPayStatus: 'XZ8261',
        reportingActionCode: 'XZ8261'
    }
};


